### ISSUE TITLE
 can we add url inline buttons there 

### ISSUE THREAD

**Issue by craziks-creator** [ESWZY/telegram-news-deploy#10]
As we are dealing with many urls so can we add inline url button with message  to make it interesting, and  how can we add  plz have a look..ty

**Comment by ESWZY** [comment]
Inline buttons for Telegram...? Do you mean you want to use button for an interactive bot? Maybe it is not supported to 
 embed a button into message.

**Comment by craziks-creator** [comment]
> Inline buttons for Telegram...? Do you mean you want to use button for an interactive bot? Maybe it is not supported to embed a button into message.
Like that:
![image](https://github.com/ESWZY/telegram-news-getting-started/assets/67502395/435a6b62-e8e0-44ac-8235-941674bb5129)

**Comment by craziks-creator** [comment]
> Inline buttons for Telegram...? Do you mean you want to use button for an interactive bot? Maybe it is not supported to embed a button into message.

Like that:
![Screenshot_20230708_235505_Telegram](https://github.com/ESWZY/telegram-news-getting-started/assets/67502395/2fee137f-e01c-44a6-beb9-1b2e3e64974f)

https://core.telegram.org/bots/2-0-intro#url-buttons

**Comment by craziks-creator** [comment]
I have an idea to implement it by adding below code [inside this](https://github.com/ESWZY/telegram-news/blob/198c6e2167f19804d0db4937020b6a6f5b63ca19/telegram_news/template/common.py#L1023) 
def _real_post(self, token, method, data):
        data['reply_markup'] = InlineKeyboardMarkup([[InlineKeyboardButton(text="TEST_BUTTON", url="www.python.org")]])
        res = requests.post('https://api.telegram.org/bot' + token + '/' + method, data, files=data['files'], proxies=self._proxies)
        return res

and this: `from pyrogram.types import InlineKeyboardButton, InlineKeyboardMarkup`

Have a look plz.. As  I want to show current url (that was parsed) and current tag name  or table name on the button, so which variable should I add in place of "www.python.org" and "TEST_BUTTON " ty

**Comment by craziks-creator** [comment]
> I have an idea to implement it by adding below code [inside this](https://github.com/ESWZY/telegram-news/blob/198c6e2167f19804d0db4937020b6a6f5b63ca19/telegram_news/template/common.py#L1023) def _real_post(self, token, method, data): data['reply_markup'] = InlineKeyboardMarkup([[InlineKeyboardButton(text="TEST_BUTTON", url="www.python.org")]]) res = requests.post('https://api.telegram.org/bot' + token + '/' + method, data, files=data['files'], proxies=self._proxies) return res
> 
> and this: `from pyrogram.types import InlineKeyboardButton, InlineKeyboardMarkup`
> 
> Have a look plz..


💫💫
It worked:)
![SmartSelect_20230710_182505_Telegram](https://github.com/ESWZY/telegram-news-getting-started/assets/67502395/e602b498-461c-414c-8437-51e7b3ab47c2)

**Comment by craziks-creator** [comment]
### second method : added below lines inside deploypolicy.py

reply_markups = {
        'inline_keyboard': [[{'text': "click here", 'url': item['link']}]]
    }
    reply_markup = json.dumps(reply_markups)

    return {
        'text': po,
        'parse_mode': parse_mode,
        'disable_web_page_preview': disable_web_page_preview,
        'reply_markup': reply_markup
    }
`


working perfectly 🤖💫

**Comment by craziks-creator** [comment]
> ### second method : added below lines inside deploypolicy.py
> reply_markups = { 'inline_keyboard': [[{'text': "click here ", 'url': item['link']}]] }
   reply_markup = json.dumps(reply_markups)
> 
> ```
> return {
>     'text': po,
>     'parse_mode': parse_mode,
>     'disable_web_page_preview': disable_web_page_preview,
>     'reply_markup': reply_markup
> }
> ```
> 
> `

> 
![SmartSelect_20230711_013840_Telegram](https://github.com/ESWZY/telegram-news-getting-started/assets/67502395/478d084f-194b-434d-a196-8f7f148476ea)


### update:  can you guide me here, which  variable should I add for showing the value of tag related to that link in the place of  "click here" ty

**Comment by ESWZY** [comment]
Sounds like you're on the verge of success!

You can try to add a selector to find the tag in page.

**Comment by craziks-creator** [comment]
> Sounds like you're on the verge of success!
> 
> You can try to add a selector to find the tag in page.

No I mean, tag or table_name that was provided for sql db for that particular link . I have been trying it for a long time but unsuccessful while I got success in getting link on button but want to change the "CLICK HERE" to Tag name or table_name . Plz Have a look...

**Comment by craziks-creator** [comment]
> > Sounds like you're on the verge of success!
> > You can try to add a selector to find the tag in page.
> 
> No I mean, tag or table_name that was provided for sql db for that particular link . I have been trying it for a long time but unsuccessful while I got success in getting link on button but want to change the "CLICK HERE" to Tag name or table_name . Plz Have a look...

Got it, Solved Thanks

**Comment by craziks-creator** [comment]
Added below line : 
`data['reply_markup'] = InlineKeyboardMarkup([[InlineKeyboardButton(text=self._tag, url=item['link'])]])`

**Finally Solved** 💯
![SmartSelect_20230711_133506_Telegram](https://github.com/ESWZY/telegram-news-getting-started/assets/67502395/27bcd0b1-7aa5-484f-8950-9bcb51ed83a5)
