### ISSUE TITLE
Multiple channel

### ISSUE THREAD

**Issue by craziks-creator** [ESWZY/telegram-news-deploy#3]
I want to add two channel. 
So i add `@channel1 @channel2` in env `CHANNEL` but it's showing error `no chat id`
Is it only for one telegram channel

**Comment by ESWZY** [comment]
You should provide channel id separately. Like `CHANNEL1` is `@channel1` and `CHANNEL2` is `@channel2`. And use those new environment variables.

Or, you can hardcode your channel id into `NewsPostman()`'s `sendList` parameter list.

**Comment by craziks-creator** [comment]
> You should provide channel id separately. Like `CHANNEL1` is `@channel1` and `CHANNEL2` is `@channel2`. And use those new environment variables.
> 
> Or, you can hardcode your channel id into `NewsPostman()`'s `sendList` parameter list.
Ok, did you mean np1 like this: 
`np1 = NewsPostman(listURLs=[url1, ], sendList=[channel,channel2, ], db=db, tag=tag1)`

**Comment by craziks-creator** [comment]
> You should provide channel id separately. Like `CHANNEL1` is `@channel1` and `CHANNEL2` is `@channel2`. And use those new environment variables.
> 
> Or, you can hardcode your channel id into `NewsPostman()`'s `sendList` parameter list.

Ok, did you mean np1 like this:

    np1 = NewsPostman(listURLs=[url1, ], 
    sendList=[channel,channel2, ], db=db, 
    tag=tag1)

**Comment by ESWZY** [comment]
> > You should provide channel id separately. Like `CHANNEL1` is `@channel1` and `CHANNEL2` is `@channel2`. And use those new environment variables.
> > Or, you can hardcode your channel id into `NewsPostman()`'s `sendList` parameter list.
> 
> Ok, did you mean np1 like this: np1 = NewsPostman(listURLs=[url1, ], sendList=[channel,channel2, ], db=db, tag=tag1)

Yes dude.

**Comment by craziks-creator** [comment]
> > > You should provide channel id separately. Like `CHANNEL1` is `@channel1` and `CHANNEL2` is `@channel2`. And use those new environment variables.
> > > Or, you can hardcode your channel id into `NewsPostman()`'s `sendList` parameter list.
> > 
> > 
> > Ok, did you mean np1 like this: np1 = NewsPostman(listURLs=[url1, ], sendList=[channel,channel2, ], db=db, tag=tag1)
> 
> Yes dude.

 Thanks 😁

**Comment by craziks-creator** [comment]
Solved!
