### ISSUE TITLE
New error in installing psycopg2   (deployment on Railway)

### ISSUE THREAD

**Issue by craziks-creator** [ESWZY/telegram-news-deploy#6]
Hey ! I I moved from heroku to railway but there's error in deployment of your git while others are working fine. Error is below, have a look plz:  

﻿#10 13.28 error: metadata-generation-failed
﻿#10 13.28
﻿#10 13.28 × Encountered error while generating package metadata.
﻿#10 13.28 ╰─> See above for output.
﻿#10 13.28
﻿#10 13.28 note: This is an issue with the package mentioned above, not pip.
﻿#10 13.28 hint: See above for details.
﻿ 
﻿#10 ERROR: process "/bin/bash -ol pipefail -c python -m venv --copies /opt/venv && . /opt/venv/bin/activate && pip install -r requirements.txt" did not complete successfully: exit code: 1
﻿ 
﻿-----
﻿> [stage-0 6/8] RUN --mount=type=cache,id=s/ae7ac31c-43d9-4ab1-bb90-1e6e1956bbee-/root/cache/pip,target=/root/.cache/pip python -m venv --copies /opt/venv && . /opt/venv/bin/activate && pip install -r requirements.txt:
﻿
﻿#10 13.27       Error: pg_config executable not found.
﻿#10 13.27
﻿#10 13.27       pg_config is required to build psycopg2 from source.  Please add the directory
﻿#10 13.27       containing pg_config to the $PATH or specify the full executable path with the
﻿#10 13.27       option:
﻿#10 13.27
﻿#10 13.27           python setup.py build_ext --pg-config /path/to/pg_config build ...
﻿ 
﻿#10 13.27
﻿#10 13.27       or with the pg_config option in 'setup.cfg'.
﻿#10 13.27
﻿#10 13.27       If you prefer to avoid building psycopg2 from source, please install the PyPI
﻿#10 13.27       'psycopg2-binary' package instead.
﻿#10 13.27
﻿#10 13.27       For further information please check the 'doc/src/install.rst' file (also at
﻿#10 13.27       <https://www.psycopg.org/docs/install.html>;).
﻿#10 13.27
﻿#10 13.27       [end of output]

﻿#10 13.28 error: metadata-generation-failed
﻿#10 13.28
﻿#10 13.28 × Encountered error while generating package metadata.
﻿#10 13.28 ╰─> See above for output.
﻿#10 13.28
﻿#10 13.28 note: This is an issue with the package mentioned above, not pip.
﻿#10 13.28 hint: See above for details.
ERROR: failed to solve: process "/bin/bash -ol pipefail -c python -m venv --copies /opt/venv && . /opt/venv/bin/activate && pip install -r requirements.txt" did not complete successfully: exit code: 1
﻿ 
﻿Error: Docker build failed

**Comment by craziks-creator** [comment]
#10 13.27       Error: pg_config executable not found.
﻿#10 13.27
﻿#10 13.27       pg_config is required to build psycopg2 from source.  Please add the directory
﻿#10 13.27       containing pg_config to the $PATH or specify the full executable path with the
﻿#10 13.27       option:
﻿#10 13.27
﻿#10 13.27           python setup.py build_ext --pg-config /path/to/pg_config build ...
﻿ 
﻿#10 13.27
﻿#10 13.27       or with the pg_config option in 'setup.cfg'.
﻿#10 13.27
﻿#10 13.27       If you prefer to avoid building psycopg2 from source, please install the PyPI
﻿#10 13.27       'psycopg2-binary' package instead.
﻿#10 13.27
﻿#10 13.27       For further information please check the 'doc/src/install.rst' file (also at
﻿#10 13.27       <[https://www.psycopg.org/docs/install.html>](https://www.psycopg.org/docs/install.html%3E);).
﻿#10 13.27
﻿#10 13.27       [end of output]

**Comment by ESWZY** [comment]
Try this solution: https://stackoverflow.com/questions/11618898/pg-config-executable-not-found

**Comment by craziks-creator** [comment]
@ESWZY did u mean : `$ pip install libpq-dev==9.4.3 psycopg2`

**Comment by craziks-creator** [comment]
Thanks once again, `sudo apt-get install libpq-dev` solved the issue.
