### ISSUE TITLE
 'NoneType' object has no attribute '_instantiate_plugins'  ( deployed on Railway )

### ISSUE THREAD

**Issue by craziks-creator** [ESWZY/telegram-news-deploy#7]
File "main.py", line 16, in <module>
﻿engine = create_engine(DATABASE_URL)
﻿File "/opt/venv/lib/python3.8/site-packages/sqlalchemy/engine/__init__.py", line 520, in create_engine
﻿return strategy.create(*args, **kwargs)
﻿File "/opt/venv/lib/python3.8/site-packages/sqlalchemy/engine/strategies.py", line 56, in create
﻿plugins = u._instantiate_plugins(kwargs)
﻿AttributeError: 'NoneType' object has no attribute '_instantiate_plugins'

Line 16: `engine = create_engine(DATABASE_URL)`
(Because I m not using heroku postgresql ,am  i getting this error Because of it?)

**Comment by craziks-creator** [comment]
### Now I have added postgreSql but there is new error:

File "main.py", line 16, in <module>
﻿engine = create_engine(DATABASE_URL)
﻿File "/opt/venv/lib/python3.8/site-packages/sqlalchemy/engine/__init__.py", line 520, in create_engine
﻿return strategy.create(*args, **kwargs)
﻿File "/opt/venv/lib/python3.8/site-packages/sqlalchemy/engine/strategies.py", line 87, in create
﻿dbapi = dialect_cls.dbapi(**dbapi_args)
﻿File "/opt/venv/lib/python3.8/site-packages/sqlalchemy/dialects/postgresql/psycopg2.py", line 778, in dbapi
﻿import psycopg2
﻿from psycopg2._psycopg import (                     # noqa
﻿ImportError: libgssapi_krb5.so.2: cannot open shared object file: No such file or directory
﻿File "/opt/venv/lib/python3.8/site-packages/psycopg2/__init__.py", line 51, in <module>

**Comment by ESWZY** [comment]
> ### Now I have added postgreSql but there is new error:
> File "main.py", line 16, in ﻿engine = create_engine(DATABASE_URL) ﻿File "/opt/venv/lib/python3.8/site-packages/sqlalchemy/engine/**init**.py", line 520, in create_engine ﻿return strategy.create(*args, **kwargs) ﻿File "/opt/venv/lib/python3.8/site-packages/sqlalchemy/engine/strategies.py", line 87, in create ﻿dbapi = dialect_cls.dbapi(**dbapi_args) ﻿File "/opt/venv/lib/python3.8/site-packages/sqlalchemy/dialects/postgresql/psycopg2.py", line 778, in dbapi ﻿import psycopg2 ﻿from psycopg2._psycopg import ( # noqa ﻿ImportError: libgssapi_krb5.so.2: cannot open shared object file: No such file or directory ﻿File "/opt/venv/lib/python3.8/site-packages/psycopg2/**init**.py", line 51, in

Your environment is missing some libraries……

**Comment by craziks-creator** [comment]
> > ### Now I have added postgreSql but there is new error:
> > File "main.py", line 16, in ﻿engine = create_engine(DATABASE_URL) ﻿File "/opt/venv/lib/python3.8/site-packages/sqlalchemy/engine/**init**.py", line 520, in create_engine ﻿return strategy.create(*args, **kwargs) ﻿File "/opt/venv/lib/python3.8/site-packages/sqlalchemy/engine/strategies.py", line 87, in create ﻿dbapi = dialect_cls.dbapi(**dbapi_args) ﻿File "/opt/venv/lib/python3.8/site-packages/sqlalchemy/dialects/postgresql/psycopg2.py", line 778, in dbapi ﻿import psycopg2 ﻿from psycopg2._psycopg import ( # noqa ﻿ImportError: libgssapi_krb5.so.2: cannot open shared object file: No such file or directory ﻿File "/opt/venv/lib/python3.8/site-packages/psycopg2/**init**.py", line 51, in
> 
> Your environment is missing some libraries……

Which one , how can I find out missing lib?

**Comment by craziks-creator** [comment]
> > ### Now I have added postgreSql but there is new error:
> > File "main.py", line 16, in ﻿engine = create_engine(DATABASE_URL) ﻿File "/opt/venv/lib/python3.8/site-packages/sqlalchemy/engine/**init**.py", line 520, in create_engine ﻿return strategy.create(*args, **kwargs) ﻿File "/opt/venv/lib/python3.8/site-packages/sqlalchemy/engine/strategies.py", line 87, in create ﻿dbapi = dialect_cls.dbapi(**dbapi_args) ﻿File "/opt/venv/lib/python3.8/site-packages/sqlalchemy/dialects/postgresql/psycopg2.py", line 778, in dbapi ﻿import psycopg2 ﻿from psycopg2._psycopg import ( # noqa ﻿ImportError: libgssapi_krb5.so.2: cannot open shared object file: No such file or directory ﻿File "/opt/venv/lib/python3.8/site-packages/psycopg2/**init**.py", line 51, in
> 
> Your environment is missing some libraries……

OK thanks , Now I am using  **psycopg2-binary** instead of **psycopg2** and it works .problem solved ... thank you
