### ISSUE TITLE
List not modified! 0 posted. Wait 10s to restart!

### ISSUE THREAD

**Issue by craziks-creator** [ESWZY/telegram-news-deploy#8]
There are 9 links in node list but it is posting none of them on channel. Issue is only for tag6 while other 5 are working properly.
**Output**:﻿
sscnr: 	List not modified! 25 posted. Wait 10s to restart!
﻿**ssc:   	List not modified! 0 posted. Wait 10s to restart**!
﻿Uksssc:	List not modified! 5 posted. Wait 10s to restart!
﻿chsl result:	0 succeeded, 25 posted. Wait 10s to restart!
﻿sscnr: 	List not modified! 25 posted. Wait 10s to restart!

Plz Have a look **Code**:

```url6="https://doc.ssc.nic.in/Portal/LatestNews/"```
tag6 = "ssc"
table_name6 = "ssc"
ie1 = InfoExtractor()
ie1.set_list_selector('div.scrollingNotifications_New>ul>li:nth-child(-n+3)>a') 
ie1.set_title_selector('#forScrollNews')  #id
ie1.set_paragraph_selector('div.scrollingNotifications_New>ul>li:nth-child(-n+3)>a[href]')
ie1.set_time_selector('span')
ie1.set_source_selector('span.sourceTemplate')
ie1.max_post_length = 2000
ie1.set_id_policy(ssc_id_policy)
np1 = NewsPostman(listURLs=[url6, ], sendList=[channel2,channel3, ], db=db, tag=tag6)
np1.set_bot_token(bot_token)
np1.set_extractor(ie1)
np1.set_table_name(table_name6)
np1.set_max_list_length(25)
np1.set_max_table_rows(25 * 3, False)
np1.poll()

**Comment by ESWZY** [comment]
> ie1.set_list_selector('div.scrollingNotifications_New>ul>li:nth-child(-n+3)>a')

I think `ie1.set_list_selector('div.eachNotification a')` is enough.

**Comment by craziks-creator** [comment]
> 

Not working same issue. Even after using the above selector `div.eachNotification a` It is showing below ouput in which **ssc** tag is not showing while other 5 tags are visible:

Uksssc:	0 succeeded, 5 posted. Wait 10s to restart!
﻿sscnr: 	0 succeeded, 25 posted. Wait 10s to restart!
﻿Uksssc:	List not modified! 5 posted. Wait 10s to restart!
﻿sscnr: 	List not modified! 25 posted. Wait 10s to restart!
﻿chsl result:	0 succeeded, 25 posted. Wait 10s to restart!
﻿others result:	0 succeeded, 12 posted. Wait 10s to restart!
﻿cgl result:	0 succeeded, 11 posted. Wait 10s to restart!
﻿Uksssc:	List not modified! 5 posted. Wait 10s to restart!
﻿sscnr: 	List not modified! 25 posted. Wait 10s to restart!
﻿chsl result:	List not modified! 25 posted. Wait 10s to restart!
﻿Set table name "sscnr" successfully, table already exists!
﻿Set table name "chsl" successfully, table already exists!
﻿Set table name "others" successfully, table already exists!
﻿Set table name "cgl" successfully, table already exists!
﻿Set table name "uksssc" successfully, table already exists!
﻿Set table name "ssc" successfully, table already exists!
﻿sscnr: 	0 succeeded, 25 posted. Wait 10s to restart!
﻿Uksssc:	0 succeeded, 5 posted. Wait 10s to restart!

**Comment by ESWZY** [comment]
If you want a mixed use of `ie`, you can use it like this: `ie1.set_list_selector('div.eachNotification a, div.scrollingNotifications_New>ul>li:nth-child(-n+3)>a')`

**Comment by craziks-creator** [comment]
> If you want a mixed use of `ie`, you can use it like this: `ie1.set_list_selector('div.eachNotification a, div.scrollingNotifications_New>ul>li:nth-child(-n+3)>a')`

That's great, but issue is unsolved , it's not posting anything on telegram  about that tag after using every selector.

**Comment by craziks-creator** [comment]
Error:
```
b4e0107fa60da08f4125104fee1b78bb empty message!
warning in ssc****
```
while in sql query:
`SELECT * FROM ssc WHERE news_id = 'b4e0107fa60da08f4125104fee1b78bb`'

**Comment by craziks-creator** [comment]
Now solved:)
added two classes of div together scrollingNotifications_New and scrollbar
```
ie1.set_list_selector('div.scrollingNotifications_New.scrollbar > ul > li:nth-child(-n+3)')
ie1.set_title_selector('#forScrollNews')  #noTitle
ie1.set_paragraph_selector('div.scrollingNotifications_New.scrollbar > ul > li:nth-child(-n+3) a[href]')

```
